version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-apache-node-browsers # The primary container where steps are run
        auth:
          username: tpenney89
          password: Greenmonster12  # context / project UI env-var reference
      - image: circleci/mysql:8.0.4
        auth:
          username: tpenney89
          password: Greenmonster12  # context / project UI env-var reference
        environment:
          #MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: quotes
          MYSQL_USER: monty
          MYSQL_PASSWORD: some_pass

    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI
          command: |
            sudo apt-get install default-mysql-client
      - run:
          mvn test


